name: test

on:
  push:
    paths:
      - 'pokemon_ai/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@master
        with:
          key: v1-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          path: |
            backend/.venv
      - name: run tests
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true # To cache python modules easilly
          poetry install
          poetry run pyright
          poetry run python -m pytest
